
ARG VARIANT="ubuntu20.04" 
ARG CUDA_VERSION="11.0.3"
FROM nvidia/cuda:${CUDA_VERSION}-devel-${VARIANT}


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
